In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [4]:
# devide data into 2 parts
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2) # text size = 0.2 means use 20% data from the data set to 'text'

In [5]:
x_train

array([17,  2, 15,  9, 20, 19, 18,  1,  7, 14,  8, 12,  6, 13, 16, 11])

In [6]:
len(x_train)

16

In [7]:
len(x_test)

4

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2, random_state=6) #'random_state' uses to give same number set as constant

In [24]:
x_train

array([ 9,  3, 16, 15,  5, 12, 13,  2, 19,  1, 17, 14, 20,  4, 10, 11])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2,shuffle=False) # not shuffle the data set

In [26]:
x_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])