In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.shape #number of raws and coloumns

(150, 6)

In [5]:
data['Species'].value_counts() 

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [7]:
data.info() # details of the data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [8]:
data.describe() # more details of the data set

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [10]:
## Species will be the target variable (y) and other 4 raws will be the features(x)

# Store features as x
x = data.iloc[:,1:5]  # iloc - index location
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [11]:
# Store target variable as y

y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [12]:
# feature scalinf the features using standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
x = scaler.fit_transform(x)
x[0:5] # display the first 5 values

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [15]:
# Divide data into train set and test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [16]:
x_train.shape

(120, 4)

In [17]:
x_test.shape

(30, 4)

In [19]:
## Train the model using KNN algorithm

from sklearn.neighbors import KNeighborsClassifier # Import KNeighborsClaffier Class
model = KNeighborsClassifier(n_neighbors=1) # creating an object for KNeighborsClaffier Class and giving k=1
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [20]:
# Predict values according to the test set

pred = model.predict(x_test)
pred[0:5] # display first 5 predicted values

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [21]:
y_test[0:5] # display first 5 actual test values

101     Iris-virginica
85     Iris-versicolor
16         Iris-setosa
67     Iris-versicolor
28         Iris-setosa
Name: Species, dtype: object

In [22]:
# Accuracy of the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy


0.9666666666666667

In [23]:
## Find Accuracy using confusin matrix

# Diagonal values give the actual values (true values it's mean real value=predicted value)
# only one value is different (it's mean real value!=predicted value)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
cm

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 10]])

In [25]:
# more details according to the accuracy

result = pd.DataFrame(data=[y_test.values,pred], index=['y_text','pred'])
result.transpose()

y_text             pred
0    Iris-virginica   Iris-virginica
1   Iris-versicolor  Iris-versicolor
2       Iris-setosa      Iris-setosa
3   Iris-versicolor  Iris-versicolor
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11  Iris-versicolor  Iris-versicolor
12      Iris-setosa      Iris-setosa
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17  Iris-versicolor  Iris-versicolor
18   Iris-virginica   Iris-virginica
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24      Iris-setosa      Iris-setosa
25      Iris-setosa      Iris-setosa
26   Iris-virginica   Iris-virginica
27   Iris-virginica  Iris-versicolor
28   Iris-virginica   Iris-virginica
29   Iris-virginica   Iris-virginica

In [36]:
## Finding a Suitable K value

# Test the model using several K values
correct_sum = []  #creating an array to store values
for i in range(1,20):   # K values from 1 to 19
    model = KNeighborsClassifier(n_neighbors=i) # create an object according to KNeighborsClassifier constructor
    model.fit(x_train,y_train) #train the model
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(int(correct))  # if the predicted value = real value, then it add to the list


In [37]:
correct_sum

[29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 28, 29, 29, 29, 29, 29, 29, 29, 29]

In [39]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  29  29  29  29  29  29  29  29  29  29  28  29  29  29  29  29  29  29  29

In [40]:
# consider K=1
model = KNeighborsClassifier(n_neighbors=8) #(k=8)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [41]:
# find the accuracy
accuracy_score(y_test,pred)

0.9666666666666667

In [42]:
# accuracy from confussion matrix
confusion_matrix(y_test,pred)

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 10]])